name: Akla-api-cd
on: 
  push: 
    branches:
      - master
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5.3.0
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish ./Restaurants.Api/Restaurants.Api.csproj --no-build -o ${{env.DOTNET_ROOT}}/api
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: api-artifact
          path: ${{env.DOTNET_ROOT}}/api


  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.1.0
        with:
          name: api-artifact
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v3.0.8
        with:
          app-name: 'Akla-api-dev'
          publish-profile: ${{secrets.PUBLISH_PROFILE_DEV}}
                

